[package]
name = "HOPA"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A lightweight, higher-order parser"
repository = "https://github.com/HigherOrderCO/HOPA"

[dependencies]
highlight_error = "0.1.1"
